version: 2

registries:
    npm-github:
        type: npm-registry
        url: https://npm.pkg.github.com
        token: ${{ secrets.READER_TOKEN }}
updates:
    -   package-ecosystem: npm
        directory: "/"
        schedule:
            interval: weekly
            day: "sunday"
            time: "04:00"
        versioning-strategy: increase
        open-pull-requests-limit: 30
        registries: "*"
        ignore:
            -   dependency-name: "*"
                update-types: [ "version-update:semver-patch" ]
        groups:
            react:
                patterns:
                    - "react"
                    - "@types/react"
                    - "react-dom"
            babel:
                patterns:
                    - "@babel/*"
            aksel:
                patterns:
                    - "@navikt/aksel-icons"
                    - "@navikt/ds-*"
                exclude-patterns:
                    - "@navikt/ds-icons"
            storybook:
                patterns:
                    - "@storybook/*"
                    - "storybook"
                exclude-patterns:
                    - "@storybook/storybook-deployer"
            commitlint:
                patterns:
                    - "@commitlint/*"
    -   package-ecosystem: github-actions
        directory: "/"
        schedule:
            interval: weekly
            day: "sunday"
            time: "04:00"
