name: Build-Deploy-Npm
on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - package.json

jobs:
  build-and-push-to-npm:
    name: Bygg og push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Prepare repository
        run: git checkout "${GITHUB_REF:11}"
      - name: Installer dependencies
        run: |
          yarn
          yarn bootstrap
      - name: Bygg
        run: yarn compile
      - name: Push
        run: |
          git config user.email "teamfamilie@nav.no"
          git config user.name "Team familie"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          yarn publish:ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}